version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3

jobs:
  test-rust:
    docker:
        - image: cimg/rust:1.70.0
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Install grcov"
          command: "cargo install grcov"
      - run:
          name: "Run tests"
          command: |
            export CARGO_INCREMENTAL=0
            export RUSTDOCFLAGS="-Cpanic=abort"
            export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
            rustup component add llvm-tools-preview
            cargo test
      - run:
          name: "Run grcov"
          command: |
            grcov . --llvm -s . -t html --branch --ignore-not-existing -o ./coverage/
            grcov . --llvm -s . -t lcov --branch --ignore-not-existing -o ./lcov.info
      - codecov/upload:
          token: CODECOV_TOKEN

workflows:
  build-and-test:
    jobs:
      - test-rust
