version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3

jobs:
  test-rust:
    docker:
        - image: cimg/rust:1.70.0
    steps:
      - checkout
      - run:
          name: "Install Tarpaulin"
          command: "cargo install cargo-tarpaulin"
      - run:
          name: "Run tests"
          command: "cargo tarpaulin --out xml"
      - codecov/upload:
          token: CODECOV_TOKEN

workflows:
  build-and-test:
    jobs:
      - test-rust
